name: Publish
on:
  push:
    branches:
      - master
      - next
      - beta
      - "*.x" # maintenance releases

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'widget-providers-template'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"

      - name: 🚀 Publish
        uses: Marfeel/github-actions/providers/widget/publish@master
        with:
          gh-token: ${{ secrets.GH_PACKAGE_REGISTRY_TOKEN }}
          nexus-token: ${{ secrets.NPM_NEXUS_AUTH }}
          build-number: ${{ github.run_id }}