name: Publish
on:
  push:
    branches:
      - master
      - next
      - beta
      - "*.x" # maintenance releases

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - name: 🚀 Publish
        uses: Marfeel/github-actions/common/actions/publish@master
        with:
          nexus-token: "test"
          build-number: ${{ github.run_id }}
